# This is a basic workflow to help you get started with Actions

name: Weather Rebot

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.mailtrap.io
          server_port: 2525
          username: 7db988b1e7d13b
          password: f67e33d0e39504
          subject: Weather Report
          body: file://result.html
          to: wangben0804@126.com
          from: GitHub Actions
          content_type: text/html

